name: Main Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-reusable-workflow:
    uses: everywhereteam/.github-private/tree/main/.github/workflows/librarybuildupdate.yml@main
    with:
      event_type: library-update
    secrets:
      ew_token: ${{ secrets.EW_TOKEN }}
