# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build/Test/Pack/Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --nologo --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: dotnet pack
      shell: bash
      run: dotnet pack -c Release --nologo --no-build --include-symbols
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    - name: dotnet push GITHUB NUGET
      shell: bash
      run: dotnet nuget push ${{ github.workspace }}/bin/**/*.nupkg --source "github" --skip-duplicate  
